---
- name: Configure LAN Connectivity Policy for iscsi booting scaleup Nodes
  vars:
    api_info:
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  block:
    - name: Check if LAN Connectivity Policy exists
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"
        resource_path: /vnic/LanConnectivityPolicies
        query_params:
          $filter: Name eq '{{ name_of_bmSU_iscsi_lan_connectivity_policy }}'
      register: existing_iSU_lan_connectivity_policy
      failed_when: false

    - name: LAN Connectivity Policy for iSCSI booting HANA Nodes
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"
        resource_path: /vnic/LanConnectivityPolicies
        query_params:
          $filter: Name eq '{{ name_of_bmSU_iscsi_lan_connectivity_policy }}'
        api_body:
          Name: "{{ name_of_bmSU_iscsi_lan_connectivity_policy }}"
          Description: "{{ description_of_bmSU_iscsi_lan_connectivity_policy }}"
          TargetPlatform: FIAttached
          AzureQosEnabled: false
          IqnAllocationType: Pool
          PlacementMode: custom
          IqnPool: "{{ iqn_pool_details.api_response.Moid }}"
          StaticIqnName: ""
          Organization:
            Moid: "{{ intersight_org.api_response.Moid }}"
          Tags:
            - Key: configmode
              Value: ansible
            - Key: prefix
              Value: "{{ prefix }}"
      when: existing_iSU_lan_connectivity_policy.api_response.Moid is not defined
      register: bmSU_iscsi_lan_connectivity_policy

    - name: Add {{ name_of_bm_iscsi_scaleup_vnic_1 }} to iscsi baremetal scaleup LAN Connectivity Policy
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"
        resource_path: /bulk/MoCloners
        query_params:
          $filter: Name eq '{{ name_of_bm_iscsi_scaleup_vnic_1 }}'
        api_body:
          Organization:
            Moid: "{{ intersight_org.api_response.Moid }}"
          Sources:
            - Moid: "{{ hanaappsrv_vnic_template.api_response.Moid }}"
              ObjectType: vnic.VnicTemplate
          Targets:
            - LanConnectivityPolicy: "{{ bmSU_iscsi_lan_connectivity_policy.api_response.Moid }}"
              MacAddressType: POOL
              Name: "{{ name_of_bm_iscsi_scaleup_vnic_1 }}"
              ObjectType: vnic.EthIf
              Order: 0
              Placement:
                AutoPciLink: true
                AutoSlotId: true
          WorkflowNameSuffix: Add vNIC from a Template
      when: existing_iSU_lan_connectivity_policy.api_response.Moid is not defined

    - name: Add {{ name_of_bm_iscsi_scaleup_vnic_2 }} to iscsi baremetal scaleup LAN Connectivity Policy
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"
        resource_path: /bulk/MoCloners
        query_params:
          $filter: Name eq '{{ name_of_bm_iscsi_scaleup_vnic_2 }}'
        api_body:
          Organization:
            Moid: "{{ intersight_org.api_response.Moid }}"
          Sources:
            - Moid: "{{ hanashared_vnic_template.api_response.Moid }}"
              ObjectType: vnic.VnicTemplate
          Targets:
            - LanConnectivityPolicy: "{{ bmSU_iscsi_lan_connectivity_policy.api_response.Moid }}"
              MacAddressType: POOL
              Name: "{{ name_of_bm_iscsi_scaleup_vnic_2 }}"
              ObjectType: vnic.EthIf
              Order: 1
              Placement:
                AutoPciLink: true
                AutoSlotId: true
          WorkflowNameSuffix: Add vNIC from a Template
      when: existing_iSU_lan_connectivity_policy.api_response.Moid is not defined

    - name: Add {{ name_of_bm_iscsi_scaleup_vnic_3 }} to iscsi baremetal scaleup LAN Connectivity Policy
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"
        resource_path: /bulk/MoCloners
        query_params:
          $filter: Name eq '{{ name_of_bm_iscsi_scaleup_vnic_3 }}'
        api_body:
          Organization:
            Moid: "{{ intersight_org.api_response.Moid }}"
          Sources:
            - Moid: "{{ hanaadmin_vnic_template.api_response.Moid }}"
              ObjectType: vnic.VnicTemplate
          Targets:
            - LanConnectivityPolicy: "{{ bmSU_iscsi_lan_connectivity_policy.api_response.Moid }}"
              MacAddressType: POOL
              Name: "{{ name_of_bm_iscsi_scaleup_vnic_3 }}"
              ObjectType: vnic.EthIf
              Order: 2
              Placement:
                AutoPciLink: true
                AutoSlotId: true
          WorkflowNameSuffix: Add vNIC from a Template
      when: existing_iSU_lan_connectivity_policy.api_response.Moid is not defined

    - name: Add {{ name_of_bm_iscsi_scaleup_vnic_4 }} to iscsi baremetal scaleup LAN Connectivity Policy
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"
        resource_path: /bulk/MoCloners
        query_params:
          $filter: Name eq '{{ name_of_bm_iscsi_scaleup_vnic_4 }}'
        api_body:
          Organization:
            Moid: "{{ intersight_org.api_response.Moid }}"
          Sources:
            - Moid: "{{ hanadata_vnic_template.api_response.Moid }}"
              ObjectType: vnic.VnicTemplate
          Targets:
            - LanConnectivityPolicy: "{{ bmSU_iscsi_lan_connectivity_policy.api_response.Moid }}"
              MacAddressType: POOL
              Name: "{{ name_of_bm_iscsi_scaleup_vnic_4 }}"
              ObjectType: vnic.EthIf
              Order: 3
              Placement:
                AutoPciLink: true
                AutoSlotId: true
          WorkflowNameSuffix: Add vNIC from a Template
      when: existing_iSU_lan_connectivity_policy.api_response.Moid is not defined

    - name: Add {{ name_of_iscsi_a_vnic }} to iscsi baremetal scaleup LAN Connectivity Policy
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"
        resource_path: /bulk/MoCloners
        query_params:
          $filter: Name eq '{{ name_of_iscsi_a_vnic }}'
        api_body:
          Organization:
            Moid: "{{ intersight_org.api_response.Moid }}"
          Sources:
            - Moid: "{{ iscsi_a_vnic_template.api_response.Moid }}"
              ObjectType: vnic.VnicTemplate
          Targets:
            - LanConnectivityPolicy: "{{ bmSU_iscsi_lan_connectivity_policy.api_response.Moid }}"
              MacAddressType: POOL
              Name: "{{ name_of_iscsi_a_vnic }}"
              ObjectType: vnic.EthIf
              Order: 4
              Placement:
                AutoPciLink: true
                AutoSlotId: true
          WorkflowNameSuffix: Add vNIC from a Template
      when: existing_iSU_lan_connectivity_policy.api_response.Moid is not defined

    - name: Add {{ name_of_iscsi_b_vnic }} to iscsi baremetal scaleup LAN Connectivity Policy
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"
        resource_path: /bulk/MoCloners
        query_params:
          $filter: Name eq '{{ name_of_iscsi_b_vnic }}'
        api_body:
          Organization:
            Moid: "{{ intersight_org.api_response.Moid }}"
          Sources:
            - Moid: "{{ iscsi_b_vnic_template.api_response.Moid }}"
              ObjectType: vnic.VnicTemplate
          Targets:
            - LanConnectivityPolicy: "{{ bmSU_iscsi_lan_connectivity_policy.api_response.Moid }}"
              MacAddressType: POOL
              Name: "{{ name_of_iscsi_b_vnic }}"
              ObjectType: vnic.EthIf
              Order: 5
              Placement:
                AutoPciLink: true
                AutoSlotId: true
          WorkflowNameSuffix: Add vNIC from a Template
      when: existing_iSU_lan_connectivity_policy.api_response.Moid is not defined

    - name: Add {{ name_of_bm_iscsi_scaleup_vnic_5 }} to iscsi baremetal scaleup LAN Connectivity Policy
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"
        resource_path: /bulk/MoCloners
        query_params:
          $filter: Name eq '{{ name_of_bm_iscsi_scaleup_vnic_5 }}'
        api_body:
          Organization:
            Moid: "{{ intersight_org.api_response.Moid }}"
          Sources:
            - Moid: "{{ hanalog_vnic_template.api_response.Moid }}"
              ObjectType: vnic.VnicTemplate
          Targets:
            - LanConnectivityPolicy: "{{ bmSU_iscsi_lan_connectivity_policy.api_response.Moid }}"
              MacAddressType: POOL
              Name: "{{ name_of_bm_iscsi_scaleup_vnic_5 }}"
              ObjectType: vnic.EthIf
              Order: 6
              Placement:
                AutoPciLink: true
                AutoSlotId: true
          WorkflowNameSuffix: Add vNIC from a Template
      when: existing_iSU_lan_connectivity_policy.api_response.Moid is not defined

    - name: Add {{ name_of_bm_iscsi_scaleup_vnic_6 }} to iscsi baremetal scaleup LAN Connectivity Policy
      cisco.intersight.intersight_rest_api:
        api_private_key: "{{ api_private_key }}"
        api_key_id: "{{ api_key_id }}"
        api_uri: "{{ api_uri | default(omit) }}"
        validate_certs: "{{ validate_certs | default(omit) }}"
        state: "{{ state | default(omit) }}"
        resource_path: /bulk/MoCloners
        query_params:
          $filter: Name eq '{{ name_of_bm_iscsi_scaleup_vnic_6 }}'
        api_body:
          Organization:
            Moid: "{{ intersight_org.api_response.Moid }}"
          Sources:
            - Moid: "{{ hanabackup_vnic_template.api_response.Moid }}"
              ObjectType: vnic.VnicTemplate
          Targets:
            - LanConnectivityPolicy: "{{ bmSU_iscsi_lan_connectivity_policy.api_response.Moid }}"
              MacAddressType: POOL
              Name: "{{ name_of_bm_iscsi_scaleup_vnic_6 }}"
              ObjectType: vnic.EthIf
              Order: 7
              Placement:
                AutoPciLink: true
                AutoSlotId: true
          WorkflowNameSuffix: Add vNIC from a Template
      when: existing_iSU_lan_connectivity_policy.api_response.Moid is not defined

