---
  - name: "Configure Intel M7 Virtualization BIOS Policy"
    cisco.intersight.intersight_bios_policy:
      api_private_key: "{{ api_private_key }}"
      api_key_id: "{{ api_key_id }}"
      organization: "{{ org_name }}"
      name: "{{ name_of_bios_policy }}"
      description: "{{ description_of_bios_policy }}"
      tags:
        - Key: "configmode"
          Value: "ansible"
        - Key: "prefix"
          Value: "{{ prefix }}"
      cdn_enable: "enabled"
      patrol_scrub: "disabled"
    register: bios_policy

